version: '3'
services:
  # Web container, only running api
  web:
    container_name: driving-api
    build: 
      context: .
      dockerfile: Dockerfile-api
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      "MONGO_PORT": 27018
      "MONGO_USER": "root"
      "MONGO_PASS": "root"
      "MONGO_DB": "driving"
      "RABBIT_USER": "root"
      "RABBIT_PASS": "root"
      "RABBIT_PORT": 5673
      "API_PORT": 2323
    ports:
      - 2323:2323
    restart: always
    volumes:
      - ./:/src

  # Worker container, running multiple workers for retrieving directions
  worker:
    container_name: driving-worker
    build:
      context: .
      dockerfile: Dockerfile-worker
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      "MONGO_PORT": 27018
      "MONGO_USER": "root"
      "MONGO_PASS": "root"
      "MONGO_DB": "driving"
      "RABBIT_USER": "root"
      "RABBIT_PASS": "root"
      "RABBIT_PORT": 5673
    restart: always
    volumes:
      - ./:/src

  # MongDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo:/data/db
    ports:
      - 27018:27017
    restart: always

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      "RABBITMQ_DEFAULT_USER": "root"
      "RABBITMQ_DEFAULT_PASS": "root"
    ports:
      - 15673:15672
      - 5673:5672
    restart: always

volumes:
  mongo: