FROM keymetrics/pm2-docker-alpine:latest

WORKDIR /src

# Install dependencies
COPY package.json /src/package.json
RUN npm install --production

COPY lib /src/lib
COPY pm2.yml /src/pm2.yml

EXPOSE 8080

# Start
CMD ["pm2-dev", "pm2.yml"]