FROM keymetrics/pm2-docker-alpine:latest

WORKDIR /src

# Install dependencies
COPY package.json /src/package.json
RUN npm install

COPY lib /src/lib
COPY pm2.worker.yml /src/pm2.worker.yml

# Start
CMD ["pm2-dev", "pm2.worker.yml"]